# Gradient Descent in Linear Regression

In [55]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [17]:
df = pd.read_csv("/home/senthil/Data/Data/Data_Base/CSV_file/auto.csv")

In [19]:
df = df.dropna()

In [20]:
x = df[['city-mpg']]
y = df[['price']]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2)

In [23]:
lm = LinearRegression()

In [24]:
lm.fit(x_train, y_train)

LinearRegression()

In [25]:
lm.predict(x_test)

array([[14189.47860361],
       [ 7755.94389257],
       [ 9185.6182728 ],
       [ 8470.78108268],
       [12759.80422338],
       [10615.29265303],
       [12044.96703326],
       [ 4181.75794199],
       [13474.6414135 ],
       [-2966.61395917],
       [ 4181.75794199],
       [12759.80422338],
       [15619.15298384],
       [15619.15298384],
       [ 8470.78108268],
       [ 8470.78108268],
       [17048.82736408],
       [18478.50174431],
       [ 9185.6182728 ],
       [11330.12984315],
       [ 8470.78108268],
       [ 8470.78108268],
       [11330.12984315],
       [11330.12984315],
       [10615.29265303],
       [12759.80422338],
       [ 8470.78108268],
       [10615.29265303],
       [17763.66455419],
       [12044.96703326],
       [13474.6414135 ],
       [17048.82736408]])

In [41]:
array(y_test.values)

array([[ 9279.],
       [ 7126.],
       [ 7295.],
       [ 6918.],
       [10198.],
       [ 7463.],
       [22470.],
       [ 7775.],
       [11199.],
       [ 5151.],
       [ 5572.],
       [10345.],
       [12170.],
       [15510.],
       [ 7499.],
       [ 6488.],
       [18620.],
       [14399.],
       [ 7295.],
       [ 8195.],
       [ 7609.],
       [ 5118.],
       [11248.],
       [ 9988.],
       [ 9258.],
       [ 6989.],
       [ 6095.],
       [13200.],
       [18150.],
       [ 8845.],
       [ 7957.],
       [11900.]])

In [47]:
pd.DataFrame({'y':y_test.values.tolist(), 'y_predict':lm.predict(x_test).tolist()})

            y             y_predict
0    [9279.0]  [14189.478603611191]
1    [7126.0]  [7755.9438925668255]
2    [7295.0]   [9185.618272798907]
3    [6918.0]   [8470.781082682865]
4   [10198.0]   [12759.80422337911]
5    [7463.0]  [10615.292653030989]
6   [22470.0]  [12044.967033263067]
7    [7775.0]   [4181.757941986623]
8   [11199.0]  [13474.641413495148]
9    [5151.0]  [-2966.613959173781]
10   [5572.0]   [4181.757941986623]
11  [10345.0]   [12759.80422337911]
12  [12170.0]   [15619.15298384327]
13  [15510.0]   [15619.15298384327]
14   [7499.0]   [8470.781082682865]
15   [6488.0]   [8470.781082682865]
16  [18620.0]  [17048.827364075354]
17  [14399.0]  [18478.501744307432]
18   [7295.0]   [9185.618272798907]
19   [8195.0]  [11330.129843147028]
20   [7609.0]   [8470.781082682865]
21   [5118.0]   [8470.781082682865]
22  [11248.0]  [11330.129843147028]
23   [9988.0]  [11330.129843147028]
24   [9258.0]  [10615.292653030989]
25   [6989.0]   [12759.80422337911]
26   [6095.0]   [8470.781082682865]
27  [13200.0]  [10615.292653030989]
28  [18150.0]   [17763.66455419139]
29   [8845.0]  [12044.967033263067]
30   [7957.0]  [13474.641413495148]
31  [11900.0]  [17048.827364075354]

In [59]:
np.squeeze(y_test)

88      9279.0
141     7126.0
35      7295.0
153     6918.0
147    10198.0
146     7463.0
203    22470.0
182     7775.0
170    11199.0
18      5151.0
21      5572.0
42     10345.0
133    12170.0
135    15510.0
96      7499.0
152     6488.0
137    18620.0
102    14399.0
36      7295.0
185     8195.0
122     7609.0
138     5118.0
177    11248.0
175     9988.0
162     9258.0
85      6989.0
51      6095.0
108    13200.0
117    18150.0
59      8845.0
119     7957.0
107    11900.0
Name: price, dtype: float64

In [60]:
lm.predict(x_test).

[[14189.478603611191],
 [7755.9438925668255],
 [9185.618272798907],
 [8470.781082682865],
 [12759.80422337911],
 [10615.292653030989],
 [12044.967033263067],
 [4181.757941986623],
 [13474.641413495148],
 [-2966.613959173781],
 [4181.757941986623],
 [12759.80422337911],
 [15619.15298384327],
 [15619.15298384327],
 [8470.781082682865],
 [8470.781082682865],
 [17048.827364075354],
 [18478.501744307432],
 [9185.618272798907],
 [11330.129843147028],
 [8470.781082682865],
 [8470.781082682865],
 [11330.129843147028],
 [11330.129843147028],
 [10615.292653030989],
 [12759.80422337911],
 [8470.781082682865],
 [10615.292653030989],
 [17763.66455419139],
 [12044.967033263067],
 [13474.641413495148],
 [17048.827364075354]]